### ISSUE TITLE
more efficient part 2

### ISSUE THREAD

**Issue by schoukri** [killsunday/adventofcode#1]
https://github.com/killsunday/adventofcode/blob/535d254278bf87bf367df7f81b645bf5ed2ec464/2018/05/index.mjs#L22

I'm trying to find a good way to submit comments about each other's code...let's see if opening up an issue works out ok :)

For part 2 your reduce function seems overly complicated. You could instead iterate over the 26 distinct units with a for loop (you only need one of the `aA` and `Aa` units, for example) and build a regexp with each unit using character class like `new RegExp('[aA]', 'g')`. That will remove the need for a case-insensitive search/replace which should speed things up a bit.

**Comment by killsunday** [comment]
I actually short circuit in the reducer before I ever run it twice.  The big thing is the loop regex to replace the whole chain... not so pretty.  It's about 2s per each pair.
